### PR TITLE
Mustache templates

### PR DESCRIPTION
**Pull request by BigBlueHat**
@kimdhamilton @msporny @gkellogg 

Not sure y'all have time or interest in reviewing all this, but I've worked scrawl to the point that it's pretty configurable.

The underlying goal here is to get it to a point where each community simply has a `config.yaml` and a `people.json` file near their minutes directory. That way `scrawl` itself can just be a command line tool and no longer need to be directly customized (i.e. forked...).

Again, if you've not got time for this, no worries! I'll let this idle here for a bit while I continue some (by hand...at this point) testing, and then merge it later.

Thoughts welcome, though!

### CODE REVIEW

**Comment by msporny** [comment]
> The underlying goal here is to get it to a point where each community simply has a config.yaml and a people.json file near their minutes directory. 

+1000 to this... no time to review, just chiming in to say that I'm very supportive. Thanks for all the hard work @BigBlueHat!

**Comment by msporny** [comment]
Also, we should probably just move scrawl out into its own repo.

**Review by kimdhamilton — APPROVED** [review]
LGTM, great work!

**Comment by BigBlueHat** [comment]
> Also, we should probably just move scrawl out into its own repo.

This is scrawl's own repo. ^_^

Thanks for the support!

**Pull request merged**
